### ISSUE TITLE
Plugin doesn't work.

### ISSUE THREAD

**Issue by kaiwk** [zgqq/mah#2]
### Problem
I cloned the latest version and installed it, but it seems can't work normally like the gif.

<img width="858" alt="2017-03-13 11 21 04" src="https://cloud.githubusercontent.com/assets/10190397/23840396/c901dab2-07df-11e7-9883-dbad56ec6bc2.png">

The input method can't work properly either.

### Environment
Java 8
OS X 10.12.3

Or should I put the `plug` config into `~/.config/mah/conf.xml`?
If there is a document or user guide, maybe it will be better.

**Comment by kaiwk** [comment]
I enabled the plugin though, but chinese input method still can't work properly, and the `Enter` key can't select the item.

**Comment by zgqq** [comment]
@kermitwk 
Sorry,i only tested mah on ArchLinux becasuse of the lack of mac machine,it works well on my machine.Few people use mah,so i didn't write a detailed user guide up to now. For this project,i hope that everyone forks it,fixs some bugs,and adds own features according to own need.Most of the project source should be very simple and be well structured.Mah solves my most of problems and has some cool features other softwares don't provide,so i really want to popularize mah.Sorry again,i will fix those bugs arising on my OS,but i really have no time to test on all platforms.
For your problem.You can refer to my config.

 https://github.com/zgqq/dotfiles/blob/master/mah/conf.xml

**Comment by kaiwk** [comment]
OK, I will check it.

 It's a nice work,  good for you!
